### ISSUE TITLE
Failed to load module: No module named droneapi.module.api. Use 'set moddebug 3' in the MAVProxy console to enable traceback

### ISSUE THREAD

**Issue by moonsummer** [djnugent/VisNav#5]
~/ardupilot/ArduCopter$ sim_vehicle.sh --console --map
~/ardupilot/ArduCopter ~/ardupilot/ArduCopter
Building sitl
// BUILDROOT=/tmp/ArduCopter.build HAL_BOARD=HAL_BOARD_SITL HAL_BOARD_SUBTYPE=HAL_BOARD_SUBTYPE_NONE TOOLCHAIN=NATIVE EXTRAFLAGS=-DGIT_VERSION="cf6d0db0"
~/ardupilot/ArduCopter
Starting up at CMAC : -35.363261,149.165230,584,353
Starting ardupilot : /home/farsight/ardupilot/ArduCopter/ArduCopter.elf -S -I0 --home -35.363261,149.165230,584,353 --model + --speedup=1
Connect tcp:127.0.0.1:5760 source_system=255
Loaded module console
Loaded module map
Running script (/home/farsight/.mavinit.scr)
Failed to load module: No module named droneapi.module.api. Use 'set moddebug 3' in the MAVProxy console to enable traceback
Failed to load module: No module named droneapi.module.api. Use 'set moddebug 3' in the MAVProxy console to enable traceback
Log Directory: 
Telemetry log: mav.tlog
MAV> Waiting for heartbeat from tcp:127.0.0.1:5760
STABILIZE> Received 555 parameters
Saved 555 parameters to mav.parm

STABILIZE>

**Comment by djnugent** [comment]
This code is dated. And for that reason no longer functions as is. You'll have to tweak the API calls to get it to run again.

**Comment by moonsummer** [comment]
I tweak API call ,this problem appear again.
